language: python
sudo: false

git:
  submodules: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=luajit2.1

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - source .travis/setenv_lua.sh

install:
  - pip install -r requirements.txt
  - luarocks install https://luarocks.org/manifests/leafo/sitegen-dev-1.rockspec

script: 
  - sitegen