language: python
sudo: false

###
# taken from: https://gist.github.com/petrbel/c3bf7e0f59c22a52f534
git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
###

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh

install:
  - pip install -r requirements.txt
  - luarocks install https://luarocks.org/manifests/leafo/sitegen-dev-1.rockspec

script: 
  - sitegen