name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v3
      with:
        luaVersion: "luajit"

    - name: checkout lapis
      run: git submodule update --init --recursive

    - uses: leafo/gh-actions-luarocks@v2

    - name: dependencies
      run: |
        sudo apt-get install -q python-pygments
        sudo apt-get install -q sassc
        sudo npm install -g coffee-script
        luarocks install --dev sitegen
        luarocks install lapis

    - name: build
      run: |
        sitegen
        tree www
