name: build_gh_pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: "luajit"

    - name: checkout lapis
      run: git submodule update --init --recursive

    - uses: leafo/gh-actions-luarocks@master

    - name: dependencies
      run: |
        sudo apt-get install -q python-pygments
        sudo apt-get install -q sassc
        sudo npm install -g coffee-script
        luarocks install --dev sitegen
        luarocks install lapis
        make vendor

    - name: build
      run: |
        sitegen

    - name: deploy to github pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: www
