name: deploy_live

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: "luajit"

    - name: checkout lapis
      run: git submodule update --init --recursive

    - uses: leafo/gh-actions-luarocks@master

    - name: dependencies
      run: |
        sudo apt-get install -q python-pygments
        sudo apt-get install -q sassc
        sudo npm install -g coffee-script
        luarocks install --dev sitegen
        luarocks install lapis
        npm install

    - name: build
      run: |
        sitegen

    - name: deploy to leafo.net/lapis-test
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        LANGUAGE: en_US.UTF-8
        LANG: en_US.UTF-8
        LC_ALL: en_US.UTF-8
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        cat known_hosts > ~/.ssh/known_hosts
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/known_hosts
        rsync -arvuzL www/ leaf@leafo.net:www/lapis
