name: update_submodule

on: [workflow_dispatch]

jobs:
  update_lapis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - run: |
        git config user.name 'autoleafo'
        git config user.email 'leafot+github@gmail.com'

    - run: git submodule update --remote
    - run: git commit -m '[workflow] update lapis submodule' lapis
    - run: git push

